[tool]
[tool.poetry]
name = "need-a-hand-be"
version = "0.1.0"
description = ""
authors = ["Mahesh Bardoliya <mpbardoliya@gmail.com>"]
packages = [
    { include = "need_a_hand_be" }
]
[tool.poetry.dependencies]
python = "~3.11"
fastapi = ">=0.115.12,<0.116.0"
uvicorn = ">=0.34.0,<0.35.0"
sqlalchemy = ">=2.0.40,<3.0.0"
alembic = ">=1.15.2,<2.0.0"
psycopg = ">=3.2.6,<4.0.0"
dotenv = ">=0.9.9,<0.10.0"
invoke = ">=2.2.0,<3.0.0"
pydantic = {extras = ["email"], version = ">=2.11.3,<3.0.0"}
pydantic-settings = ">=2.8.1,<3.0.0"
psycopg2-binary = ">=2.9.10,<3.0.0"
jwt = ">=1.3.1,<2.0.0"
bcrypt = ">=4.3.0,<5.0.0"
python-jose = ">=3.4.0,<4.0.0"
python-dotenv = ">=1.1.0,<2.0.0"
typer = ">=0.15.2,<0.16.0"
python-multipart = ">=0.0.20,<0.0.21"
pyhumps = "^3.8.0"

[tool.poetry.group.dev.dependencies]
pytest = "^9.0.3"
httpx = "^0.28.1"
pytest-asyncio = "^1.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
