import os

import click
from invoke import Exit, task

MODULE = "need_a_hand_be"
MAIN_APP = f"{MODULE}.main:app"


def check_project_root(c):
    """Check if we are in the project root directory."""
    if not os.path.exists("tasks.py"):
        raise Exit("Not in project root directory.")


@task
def virtualenv_run(c, cmd, *args, **kwargs):
    """Run a command in the virtualenv."""

    c.run("poetry run " + cmd, *args, **kwargs)


@task
def init_virtualenv(c):
    """Initialize python virtualenv."""
    check_project_root(c)
    c.run("poetry install")


@task
def setup(c):
    """Set up application and development components."""
    init_virtualenv(c)


@task
def debug_server(c):
    """Run debug server."""
    virtualenv_run(
        c,
        f"uvicorn {MAIN_APP} --reload",
    )


@task
def new_db_migration(c, message):
    """Create a new autogenerated db migration."""
    virtualenv_run(
        c,
        f'poetry run alembic revision --autogenerate -m "{message}"',
    )


@task
def upgrade_db(c, revision="head"):
    """Upgrade database."""
    virtualenv_run(
        c,
        f"poetry run alembic upgrade {revision}",
    )


@task
def downgrade_db(c, revision="-1"):
    """Upgrade database."""
    if not click.confirm(
        "Data will be lost if database is downgraded. Continue anyway?"
    ):
        return
    virtualenv_run(
        c,
        f"poetry run alembic downgrade {revision}",
    )
