import os

import click
from invoke import Exit
from invoke import task

MODULE = "need_a_hand_be"
MAIN_APP = f"{MODULE}.main:app"


def check_project_root(c):
    """Check if we are in the project root directory."""
    if not os.path.exists("tasks.py"):
        raise Exit("Not in project root directory.")


@task
def virtualenv_run(c, cmd, *args, **kwargs):
    """Run a command in the virtualenv."""

    c.run("poetry run " + cmd, *args, **kwargs)


@task
def init_virtualenv(c):
    """Initialize python virtualenv."""
    check_project_root(c)
    c.run("poetry install")


@task
def setup(c):
    """Set up application and development components."""
    init_virtualenv(c)


@task
def run(c):
    """Run debug server."""
    virtualenv_run(
        c,
        f"uvicorn {MAIN_APP} --reload",
    )


@task
def migrate(c, message, no_auto=False):
    """Create a new autogenerated db migration."""
    if no_auto:
        virtualenv_run(
            c,
            f'dotenv run python -m alembic revision -m "{message}"',
        )
    else:
        virtualenv_run(
            c,
            f'dotenv run python -m alembic revision --autogenerate -m "{message}"',
        )


@task
def upgrade_db(c, revision="head"):
    """Upgrade database."""
    virtualenv_run(
        c,
        f"dotenv run python -m alembic upgrade {revision}",
    )


@task
def downgrade_db(c, revision="-1"):
    """Upgrade database."""
    if not click.confirm(
        "Data will be lost if database is downgraded. Continue anyway?"
    ):
        return
    virtualenv_run(
        c,
        f"dotenv run python -m alembic downgrade {revision}",
    )
