"""initial_migration

Revision ID: 218e600bf136
Revises:
Create Date: 2025-05-04 14:33:03.568425

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "218e600bf136"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("username", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_users_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_users_updated_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("id", name=op.f("uq_users_id")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
        sa.UniqueConstraint("uuid", name=op.f("uq_users_uuid")),
    )
    op.create_index(
        op.f("ix_users_created_by_user_id"),
        "users",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_users_updated_by_user_id"),
        "users",
        ["updated_by_user_id"],
        unique=False,
    )
    op.create_table(
        "help_requests",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("location", sa.Text(), nullable=False),
        sa.Column("radius_meters", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_help_requests_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_help_requests_updated_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_help_requests_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_help_requests")),
        sa.UniqueConstraint("id", name=op.f("uq_help_requests_id")),
        sa.UniqueConstraint("uuid", name=op.f("uq_help_requests_uuid")),
    )
    op.create_index(
        op.f("ix_help_requests_created_by_user_id"),
        "help_requests",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_help_requests_updated_by_user_id"),
        "help_requests",
        ["updated_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_help_requests_user_id"), "help_requests", ["user_id"], unique=False
    )
    op.create_table(
        "help_offers",
        sa.Column("help_request_id", sa.Integer(), nullable=False),
        sa.Column("helper_id", sa.Integer(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("is_accepted", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_help_offers_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["help_request_id"],
            ["help_requests.id"],
            name=op.f("fk_help_offers_help_request_id_help_requests"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["helper_id"],
            ["users.id"],
            name=op.f("fk_help_offers_helper_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_help_offers_updated_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_help_offers")),
        sa.UniqueConstraint("id", name=op.f("uq_help_offers_id")),
        sa.UniqueConstraint("uuid", name=op.f("uq_help_offers_uuid")),
    )
    op.create_index(
        op.f("ix_help_offers_created_by_user_id"),
        "help_offers",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_help_offers_updated_by_user_id"),
        "help_offers",
        ["updated_by_user_id"],
        unique=False,
    )
    op.create_table(
        "ratings",
        sa.Column("help_request_id", sa.Integer(), nullable=False),
        sa.Column("reviewer_id", sa.Integer(), nullable=False),
        sa.Column("reviewee_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_ratings_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["help_request_id"],
            ["help_requests.id"],
            name=op.f("fk_ratings_help_request_id_help_requests"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewee_id"],
            ["users.id"],
            name=op.f("fk_ratings_reviewee_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.id"],
            name=op.f("fk_ratings_reviewer_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_ratings_updated_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ratings")),
        sa.UniqueConstraint(
            "help_request_id", "reviewer_id", "reviewee_id", name="uq_rating"
        ),
        sa.UniqueConstraint("id", name=op.f("uq_ratings_id")),
        sa.UniqueConstraint("uuid", name=op.f("uq_ratings_uuid")),
    )
    op.create_index(
        op.f("ix_ratings_created_by_user_id"),
        "ratings",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ratings_updated_by_user_id"),
        "ratings",
        ["updated_by_user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ratings_updated_by_user_id"), table_name="ratings")
    op.drop_index(op.f("ix_ratings_created_by_user_id"), table_name="ratings")
    op.drop_table("ratings")
    op.drop_index(op.f("ix_help_offers_updated_by_user_id"), table_name="help_offers")
    op.drop_index(op.f("ix_help_offers_created_by_user_id"), table_name="help_offers")
    op.drop_table("help_offers")
    op.drop_index(op.f("ix_help_requests_user_id"), table_name="help_requests")
    op.drop_index(
        op.f("ix_help_requests_updated_by_user_id"), table_name="help_requests"
    )
    op.drop_index(
        op.f("ix_help_requests_created_by_user_id"), table_name="help_requests"
    )
    op.drop_table("help_requests")
    op.drop_index(op.f("ix_users_updated_by_user_id"), table_name="users")
    op.drop_index(op.f("ix_users_created_by_user_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
